version: "2"
run:
  modules-download-mode: readonly
  tests: true
linters:
  enable:
    - gocritic
    - gocyclo
    - misspell
    - revive
    - unparam
  settings:
    gocritic:
      disabled-checks:
        - commentFormatting
      enabled-tags:
        - diagnostic
        - performance
        - style
    gocyclo:
      min-complexity: 15
    revive:
      rules:
        - name: var-naming
          disabled: true
        - name: exported
          disabled: false
  exclusions:
    generated: lax
    rules:
      - linters:
          - dupl
          - errcheck
          - gocyclo
          - gosec
        path: _test\.go
      - linters:
          - all
        path: vendor/
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
